"""add group code to users

Revision ID: c4b37749dad0
Revises: dd9f753b4abf
Create Date: 2026-10-06 19:06:43.660465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b37749dad0'
down_revision: Union[str, Sequence[str], None] = 'dd9f753b4abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_code', sa.String(length=50), nullable=False))
    op.create_foreign_key('fk_users_group_code', 'users', 'groups', ['group_code'], ['group_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_group_code', 'users', type_='foreignkey')
    op.drop_column('users', 'group_code')
    # ### end Alembic commands ###
