"""create groups table

Revision ID: dd9f753b4abf
Revises: f9ff6628bab4
Create Date: 2026-10-06 18:51:30.210313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9f753b4abf'
down_revision: Union[str, Sequence[str], None] = 'f9ff6628bab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('group_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
