# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - axtrax-trail-api-bkp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv antenv
          antenv/bin/python -m pip install --upgrade pip
          antenv/bin/python -m pip install -r requirements.txt

      - name: Run Azure PostgreSQL migrations
        env:
          DB_HOST: ${{ secrets.AZURE_DB_HOST }}
          DB_PORT: ${{ secrets.AZURE_DB_PORT }}
          DB_NAME: ${{ secrets.AZURE_DB_NAME }}
          DB_USER: ${{ secrets.AZURE_DB_USER }}
          DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          DB_SSLMODE: require

        run: |
          antenv/bin/alembic upgrade head

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

      # 🚫 Opting Out of Oryx Build
      # If you prefer to disable the Oryx build process during deployment, follow these steps:
      # 1. Remove the SCM_DO_BUILD_DURING_DEPLOYMENT app setting from your Azure App Service Environment variables.
      # 2. Refer to sample workflows for alternative deployment strategies: https://github.com/Azure/actions-workflow-samples/tree/master/AppService
      

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D6AD441814B4B9E98EE98CF3F6C5457 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_088F40650E8C467DA6B83F3608066B55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F10EFE7C8FC3426BA3F4FED9C330816B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'axtrax-trail-api-bkp'
          slot-name: 'Production'
          
